name: Parlay AI Scanner

on:
  schedule:
    - cron: "0 1 * * *"
    - cron: "0 7 * * *"
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
