name: Parlay AI Scanner

on:
  workflow_dispatch: # Tombol manual di web GitHub tetap aktif
  schedule:
    # Menggunakan waktu standar UTC (WITA dikurangi 8 jam)
    - cron: '0 9 * * *'   # 09:00 UTC = Jam 17:00 WITA (5 Sore) otomatis jalan
    - cron: '0 13 * * *'  # 13:00 UTC = Jam 21:00 WITA (9 Malam) otomatis jalan

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          ODDSPAPI_API_KEY: ${{ secrets.ODDSPAPI_API_KEY }}
          BAI_API_KEY: ${{ secrets.BAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
